### ISSUE TITLE
Unable to specify the host to listen on if choose webhook-based bot

### ISSUE THREAD

**Issue by igor-ramazanov** [augustjune/canoe#183]
By default it is a `127.0.0.1` which doesn't work well in a Docker container.

**Comment by igor-ramazanov** [comment]
More information: https://pythonspeed.com/articles/docker-connection-refused/

**Comment by augustjune** [comment]
I was not aware of this issue. Thanks for bringing this up 👍

**Comment by igor-ramazanov** [comment]
Hey, can you please push a new version, so I don't use a modified `lib/canoe_2.13.jar` as a dirty hack?
