### ISSUE TITLE
Caption in multipart request has unnecessary quotes

### ISSUE THREAD

**Issue by udzin** [augustjune/canoe#221]
When sending any media file with caption user sees quoted message.
If parseMode html or markdown enabled then telegram returns error.
#220

**Comment by udzin** [comment]
#220

**Comment by augustjune** [comment]
Hi @udzin 
Can you provide an example of the message you get the error for?
I've just tried sending a photo with a caption and both Markdown and HTML mode, and all worked fine for me 🤔

**Comment by udzin** [comment]
I get the error "org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request" when trying to send voice message from bytes
```
    SendVoice(Chat(chatId.value),InputFile.fromBytes("AudioRecord", audioRecord.bytes),
      caption = Some("test caption"),
      parseMode = Some(ParseMode.HTML)
    ).call
```
same error for ParseMode.Markdown

If i set parseMode to None then i see the quoted message in telegram
![image](https://user-images.githubusercontent.com/6111385/98507745-07fb4c80-2280-11eb-9109-b67388c5caab.png)

**Comment by augustjune** [comment]
Thank you.

I guess, we can tackle file input from bytes in a separate issue.
