### ISSUE TITLE
`.delete` method on user message not allowed

### ISSUE THREAD

**Issue by oskin1** [augustjune/canoe#54]
`.delete` method illustrated in exaples seems to be disallowed by Telegram API https://github.com/augustjune/canoe/blob/e2734e0570afdb5234868eddc326579a14d477ea/examples/src/main/scala/samples/Composition.scala#L78
Application fails with the following error:
`org.http4s.client.UnexpectedStatus: unexpected HTTP status: 405 Method Not Allowed`

**Comment by augustjune** [comment]
Hi
`MessageApi#delete` method does delete the message, but it has several restrictions that should be met for the method to succeed. You can find them in the documentation for the method. https://github.com/augustjune/canoe/blob/e2734e0570afdb5234868eddc326579a14d477ea/core/src/main/scala/canoe/api/models/MessageApi.scala#L19-L25
Make sure these limitations are satisfied in your use case.

**Comment by oskin1** [comment]
@augustjune, thank you!
